version: "3"
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./sourcefiles/nginx:/etc/nginx/conf.d
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #Postgres Service
  db:
    image: postgres:9.5-alpine
    container_name: db
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shopping-cart
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
